# yaml-language-server: $schema=./node_modules/envio/evm.schema.json

name: IntentScan
description: Enhanced Nexus Intent Explorer - Indexing Solver Transactions
unordered_multichain_mode: true
preload_handlers: true

contracts:
  - name: USDC
    abi_file_path: ./abis/erc20.json
    handler: ./src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"

networks:
  - id: 11155111  # Ethereum Sepolia
    start_block: 7200000
    contracts:
      - name: USDC
        address: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"

  - id: 421614  # Arbitrum Sepolia
    start_block: 87000000
    contracts:
      - name: USDC
        address: "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"

  - id: 84532  # Base Sepolia
    start_block: 18000000
    contracts:
      - name: USDC
        address: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"

  - id: 11155420  # Optimism Sepolia
    start_block: 19000000
    contracts:
      - name: USDC
        address: "0x5fd84259d66Cd46123540766Be93DFE6D43130D7"

  - id: 80002  # Polygon Amoy
    start_block: 15000000
    contracts:
      - name: USDC
        address: "0x41E94Eb019C0762f9Bfcf9Fb1E58725BfB0e7582"
