# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: avail-nexus-explorer
description: Avail Nexus Intent Explorer
unordered_multichain_mode: true
raw_events: true
preload_handlers: true

field_selection:
  transaction_fields:
    - hash
    - from
    - to
    - gasUsed
    - gasPrice

contracts:
  - name: VaultContractV2
    abi_file_path: ./abis/vault_abi_v2.json
    handler: ./src/EventHandlers.ts
    events:
      - event: "Deposit(bytes32 indexed requestHash, address from, bool gasRefunded)"
      - event: "Fill(bytes32 indexed requestHash, address from, address solver)"
      - event: "Settle(uint256 indexed nonce, address[] solver, address[] token, uint256[] amount)"

networks:
  - id: 421614
    start_block: 0
    contracts:
      - name: VaultContractV2
        address: "0xF0111EdE031a4377C34A4AD900f1E633E41055Dc"

  - id: 11155420
    start_block: 0
    contracts:
      - name: VaultContractV2
        address: "0xF0111EdE031a4377C34A4AD900f1E633E41055Dc"

  - id: 80002
    start_block: 0
    contracts:
      - name: VaultContractV2
        address: "0xF0111EdE031a4377C34A4AD900f1E633E41055Dc"

  - id: 84532
    start_block: 0
    contracts:
      - name: VaultContractV2
        address: "0xF0111EdE031a4377C34A4AD900f1E633E41055Dc"

  - id: 11155111
    start_block: 0
    contracts:
      - name: VaultContractV2
        address: "0xF0111EdE031a4377C34A4AD900f1E633E41055Dc"

  - id: 10143
    start_block: 0
    contracts:
      - name: VaultContractV2
        address: "0xF0111EdE031a4377C34A4AD900f1E633E41055Dc"
